backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
  ### enable below lines for github integration ###
  # name: github
  # repo: AndyWebster/postcard-poem
media_folder: 'public/img'
public_folder: '/img'

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
publish_mode: editorial_workflow
collections:
  - label: 'Blog'
    name: 'blog'
    folder: 'content/posts'
    create: true
    editor:
      preview: false
    fields:
      - { label: Title, name: title, widget: string }
      - { label: 'Preview text', name: description, widget: text }
      - { label: Collection, name: collection, widget: string, required: false }
      - {
          label: 'Aspect',
          name: aspect,
          widget: select,
          options: ['landscape', 'portrait'],
          default: landscape,
        }
      - {
          label: Image,
          name: image,
          widget: image,
          hint: Will only show if a video ID is not provided,
          choose_url: true,
        }
      - {
          label: Video,
          name: video,
          widget: string,
          hint: Vimeo video Id e.g. 770190133,
          required: false,
        }
      - {
          label: Meta Image,
          name: metaImage,
          widget: image,
          choose_url: true,
          hint: Image shown in share links and search engines (follow Facebook’s recommendation of a minimum dimension of 1200×630 pixels and an aspect ratio of 1.91:1,
          but adhere to Twitter’s file size requirement of less than 1MB),
        }
      - { label: 'Image Alt', name: alt, widget: string }
      - { label: Poem, name: poem, widget: text }
      - {
          label: Align Poem Left,
          name: alignPoemLeft,
          widget: boolean,
          default: false,
        }
        - {
          label: Hide postcard padding,
          name: removePostcardPadding,
          widget: boolean,
          default: false,
          hint: 'Remove white space around the outside of the postcard image. Works best when the image has no built-in whitespace'
        }
      - { label: 'Address lines', name: address, widget: text }
      - { label: Stamp, name: stamp, widget: image, choose_url: true }
      - {
          label: Show stamp in preview,
          name: showStampInPreview,
          widget: boolean,
          default: false,
        }
      - {
          label: Author,
          name: author,
          widget: string,
          default: 'Caroline Whitehouse',
        }
      - { label: 'Publish Date', name: date, widget: datetime }
      - { label: Body, name: body, widget: markdown, required: false }
  - label: 'Settings'
    name: 'settings'
    editor:
      preview: false
    files:
      - label: 'Home content'
        name: home
        file: 'content/home.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Welcome message', name: 'welcome', widget: 'text' }
          - { label: 'Masthead image', name: 'image', widget: image }
      - label: 'About content'
        name: about
        file: 'content/about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: Body, name: body, widget: markdown, required: true }
      - label: 'Navigation'
        name: 'items'
        file: 'content/navigation.yaml'
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: true
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
          - label: Collections
            name: collections
            widget: list
            allow_add: true
            collapsed: false
            fields:
              - { label: Label, name: text, widget: string }
              - { label: 'Image', name: 'image', widget: image }
      - label: 'Settings'
        name: 'settings'
        file: 'content/settings.yaml'
        fields:
          - {
              label: Name,
              name: name,
              widget: string,
              hint: Title shown in share links and search engines,
            }
          - {
              label: Author,
              name: author,
              widget: string,
              hint: Author shown in site footer,
            }
          - {
              label: Description,
              name: description,
              widget: text,
              hint: Description shown in share links and search engines,
            }
          - {
              label: Meta Image,
              name: metaImage,
              widget: image,
              choose_url: true,
              hint: Image shown in share links and search engines (follow Facebook’s recommendation of a minimum dimension of 1200×630 pixels and an aspect ratio of 1.91:1,
              but adhere to Twitter’s file size requirement of less than 1MB),
            }
          - {
              label: Url,
              name: url,
              widget: string,
              hint: Url shown in share links and search engines,
            }
          - {
              label: Logo,
              name: image,
              widget: image,
              choose_url: true,
              hint: Logo shown in site header,
            }
